services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    env_file:
      - backend/.env # Load the backend environment variables
      
  frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend